/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project.turn.turn.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.project.turn.turn.EnumerationType;
import org.xtext.project.turn.turn.EnumerationTypeKind;
import org.xtext.project.turn.turn.TurnPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Enumeration Type Kind</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.turn.turn.impl.EnumerationTypeKindImpl#getEnumerationType <em>Enumeration Type</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EnumerationTypeKindImpl extends DatatypeKindImpl implements EnumerationTypeKind
{
  /**
   * The cached value of the '{@link #getEnumerationType() <em>Enumeration Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getEnumerationType()
   * @generated
   * @ordered
   */
  protected EnumerationType enumerationType;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EnumerationTypeKindImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TurnPackage.Literals.ENUMERATION_TYPE_KIND;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EnumerationType getEnumerationType()
  {
    if (enumerationType != null && enumerationType.eIsProxy())
    {
      InternalEObject oldEnumerationType = (InternalEObject)enumerationType;
      enumerationType = (EnumerationType)eResolveProxy(oldEnumerationType);
      if (enumerationType != oldEnumerationType)
      {
        if (eNotificationRequired())
          eNotify(new ENotificationImpl(this, Notification.RESOLVE, TurnPackage.ENUMERATION_TYPE_KIND__ENUMERATION_TYPE, oldEnumerationType, enumerationType));
      }
    }
    return enumerationType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EnumerationType basicGetEnumerationType()
  {
    return enumerationType;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setEnumerationType(EnumerationType newEnumerationType)
  {
    EnumerationType oldEnumerationType = enumerationType;
    enumerationType = newEnumerationType;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TurnPackage.ENUMERATION_TYPE_KIND__ENUMERATION_TYPE, oldEnumerationType, enumerationType));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TurnPackage.ENUMERATION_TYPE_KIND__ENUMERATION_TYPE:
        if (resolve) return getEnumerationType();
        return basicGetEnumerationType();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TurnPackage.ENUMERATION_TYPE_KIND__ENUMERATION_TYPE:
        setEnumerationType((EnumerationType)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TurnPackage.ENUMERATION_TYPE_KIND__ENUMERATION_TYPE:
        setEnumerationType((EnumerationType)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TurnPackage.ENUMERATION_TYPE_KIND__ENUMERATION_TYPE:
        return enumerationType != null;
    }
    return super.eIsSet(featureID);
  }

} //EnumerationTypeKindImpl
