/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project.turn.turn;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Datatype Kind</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.project.turn.turn.TurnPackage#getDatatypeKind()
 * @model
 * @generated
 */
public interface DatatypeKind extends EObject
{
} // DatatypeKind
