/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project.turn.turn;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enumeration Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.turn.turn.EnumerationType#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.project.turn.turn.EnumerationType#getEnumLiteral <em>Enum Literal</em>}</li>
 *   <li>{@link org.xtext.project.turn.turn.EnumerationType#getEnumLiterals <em>Enum Literals</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.turn.turn.TurnPackage#getEnumerationType()
 * @model
 * @generated
 */
public interface EnumerationType extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.project.turn.turn.TurnPackage#getEnumerationType_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.project.turn.turn.EnumerationType#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Enum Literal</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.project.turn.turn.EnumerationLiteral}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Enum Literal</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enum Literal</em>' containment reference list.
   * @see org.xtext.project.turn.turn.TurnPackage#getEnumerationType_EnumLiteral()
   * @model containment="true"
   * @generated
   */
  EList<EnumerationLiteral> getEnumLiteral();

  /**
   * Returns the value of the '<em><b>Enum Literals</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Enum Literals</em>' attribute list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enum Literals</em>' attribute list.
   * @see org.xtext.project.turn.turn.TurnPackage#getEnumerationType_EnumLiterals()
   * @model unique="false"
   * @generated
   */
  EList<String> getEnumLiterals();

} // EnumerationType
