/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project.turn.turn;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enumeration Type Kind</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.turn.turn.EnumerationTypeKind#getEnumerationType <em>Enumeration Type</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.turn.turn.TurnPackage#getEnumerationTypeKind()
 * @model
 * @generated
 */
public interface EnumerationTypeKind extends DatatypeKind
{
  /**
   * Returns the value of the '<em><b>Enumeration Type</b></em>' reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Enumeration Type</em>' reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Enumeration Type</em>' reference.
   * @see #setEnumerationType(EnumerationType)
   * @see org.xtext.project.turn.turn.TurnPackage#getEnumerationTypeKind_EnumerationType()
   * @model
   * @generated
   */
  EnumerationType getEnumerationType();

  /**
   * Sets the value of the '{@link org.xtext.project.turn.turn.EnumerationTypeKind#getEnumerationType <em>Enumeration Type</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Enumeration Type</em>' reference.
   * @see #getEnumerationType()
   * @generated
   */
  void setEnumerationType(EnumerationType value);

} // EnumerationTypeKind
