/**
 * generated by Xtext 2.15.0
 */
package org.xtext.project.turn.turn;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum Initialization</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.project.turn.turn.EnumInitialization#getValue <em>Value</em>}</li>
 * </ul>
 *
 * @see org.xtext.project.turn.turn.TurnPackage#getEnumInitialization()
 * @model
 * @generated
 */
public interface EnumInitialization extends Initialization
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Value</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' containment reference.
   * @see #setValue(EnumerationLiteral)
   * @see org.xtext.project.turn.turn.TurnPackage#getEnumInitialization_Value()
   * @model containment="true"
   * @generated
   */
  EnumerationLiteral getValue();

  /**
   * Sets the value of the '{@link org.xtext.project.turn.turn.EnumInitialization#getValue <em>Value</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' containment reference.
   * @see #getValue()
   * @generated
   */
  void setValue(EnumerationLiteral value);

} // EnumInitialization
