/*
 * generated by Xtext 2.15.0
 */
package org.xtext.project.turn.scoping;

import org.eclipse.xtext.xbase.scoping.batch.XbaseBatchScopeProvider;

public abstract class AbstractTurnScopeProvider extends XbaseBatchScopeProvider {
}
